Name = input("Enter name : ")
Username = input("Enter username : ")
Age = input("Enter age : ")
Bio = input("Enter bio : ")
Country = input("Enter country : ")
Email = input("Enter email : ")

print("\nUSER PROFILE")
print("------------")
print("\nName: ",Name.upper())
print("Username: ",Username)
print("Age: ",Age)
print("Bio: ",Bio)
print("Country: ",Country.upper())
print("Email: ",Email.lower())